logging:
   level:
      root: INFO
      com.lckp.jproxy: DEBUG

rule:
   location: http://127.0.0.1:8117
   location-backup: http://127.0.0.1:8117

time:
   cache-expires: 4320
   token-expires: 10080
   sync-interval: 3
   sonarr-title-sync: 0 0 0/1 * * ?
   sonarr-rule-sync: 0 15 0 * * ?
   sonarr-rename: 0/30 * * * * ?
   sonarr-rename-fall-back: 30
   radarr-title-sync: 0 30 0/1 * * ?
   radarr-rule-sync: 0 45 1 * * ?
   radarr-rename: 0 0/1 * * * ?
   radarr-rename-fall-back: 6
   downloader-login: 0 */30 * * * ?

rename:
   file: true

spring:
   devtools:
      restart:
         enabled: true
         additional-paths: src/main/java
         additional-exclude: META-INF/additional-spring-configuration-metadata.json
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
   datasource:
      url: jdbc:sqlite::resource:database/jproxy.db
      driver-class-name: org.sqlite.JDBC

springdoc:
   swagger-ui:
      path: /swagger-ui.html
      tags-sorter: alpha
      operations-sorter: alpha
   api-docs:
      path: /v3/api-docs
   group-configs:
   -  group: default
      paths-to-match: /api/**
knife4j:
   enable: true
   setting:
      language: zh_cn
      swagger-model-name: 实体类列表