logging:
   level:
      root: INFO
      com.lckp.jproxy: INFO

rule:
   location: https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/rule
   location-backup: https://github.rn.lckp.top/LuckyPuppy514/jproxy/main/src/main/resources/rule

time:
   cache-expires: ${CACHE_EXPIRES:4320}
   token-expires: ${TOKEN_EXPIRES:10080}
   sync-interval: ${SYNC_INTERVAL:3}
   sonarr-title-sync: 0 0 0/1 * * ?
   sonarr-rule-sync: 0 15 0 * * ?
   sonarr-rename: 0/30 * * * * ?
   sonarr-rename-fall-back: 10
   radarr-title-sync: 0 30 0/1 * * ?
   radarr-rule-sync: 0 45 1 * * ?
   radarr-rename: 0 0/1 * * * ?
   radarr-rename-fall-back: 10
   downloader-login: 0 */30 * * * ?

spring:
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
   datasource:
      url: jdbc:sqlite:./database/jproxy.db
      driver-class-name: org.sqlite.JDBC

springdoc:
   swagger-ui:
      enabled: false
   api-docs:
      enabled: false
knife4j:
   production: true