format:
  enable: true
  official:
    anime:
      search:
        - match: "Meitantei Conan"
          replace: "名侦探柯南"
          
      common:
        - match: "第一季"
          replace: "S1"
        - match: "第二季"
          replace: "S2"
        - match: "第三季"
          replace: "S3"
        - match: "第四季"
          replace: "S4"
        - match: "第五季"
          replace: "S5"
        - match: "第六季"
          replace: "S6"
        - match: "第七季"
          replace: "S7"
        - match: "第八季"
          replace: "S8"
        - match: "Season"
          replace: "S"
        - match: "S0(\\d+)"
          replace: "S$1"
          
      accurate:
        - match: "\\[Skymoon-Raws\\]\\[(.*) ([^ ]*)\\]\\[(\\d+)](.*)"
          replace: "[Skymoon-Raws] $2 / $1 $3 $4"
          
        - match: "\\[(OPFans枫雪动漫|OPFans楓雪動漫)\\]\\[(.*) ([^ ]*)]\\[第(\\d+)(话|話)\\](.*)"
          replace: "[$1] $3 / $2 $4 $6[简体]"
          
        - match: "\\[(爱恋&漫猫字幕组|愛戀&漫貓字幕組)\\](.*)\\[([a-zA-Z].*)\\]\\[(\\d+)\\](.*)"
          replace: "[$1]$2 $3 $4 $5"
          
        - match: "【喵萌奶茶屋】.*\\[(.*)/([a-zA-Z].*)\\]\\[(\\d+)\\](.*)"
          replace: "[喵萌奶茶屋] $1 / $2 $3 $4"
          
        - match: "\\[悠哈璃羽字幕社\\] \\[(.*)_(.*)\\] \\[(\\d+)\\](.*)"
          replace: "[悠哈璃羽字幕社] $2 $3$4"
          
        - match: "【(千夏字幕组|千夏字幕組)】【(.*)_(.*)】\\[第(\\d+)(话|話)\\](.*)"
          replace: "[$1] $3 $4 $6"
          
        - match: "\\[(.*)&LoliHouse\\] ([a-zA-Z].*) / (.*) - (.*) "
          replace: "[$1&LoliHouse] $3 / $2 $4"
          
        - match: "【(幻樱字幕组|幻櫻字幕組)】【(.*)】【([^a-zA-Z]*)([a-zA-Z].*)】【(\\d+)】【([^【】]*)】【([^【】]*)】.*"
          replace: "[$1] $3 / $4 $5 [$6][$7]"
          
        - match: "\\[猎户不鸽发布组\\] ([^a-rt-zA-RT-Z]+) ([a-zA-Z].*) \\[(\\d+)\\](.*)"
          replace: "[猎户不鸽发布组] $1 / $2 $3$4"
          
        - match: "\\[ANi\\] (.*) - (.*)\\s*[-|\\[]\\s*(\\d+)[ \\]](.+)"
          replace: "$1 $3 $4[简中]"
          
        - match: "\\[猎户随缘发布组\\] ([^ ]*) ([a-zA-Z].*) \\[(\\d+)\\](.*)"
          replace: "[猎户随缘发布组] $1 / $2 $3$4"
          
        - match: "\\[Lilith-Raws\\](.*)Shijou Saikyou no Daimaou"
          replace: "[Lilith-Raws]$1Shijou Saikyou no Daimaou, Murabito A ni Tensei suru"
          
        - match: "\\[NC-Raws\\] (.*) \\/ (.*) - (\\d+)(.*)"
          replace: "[NC-Raws] $1 / $2 $3$4 [简中\\]"
          
        - match: "\\[(银色子弹字幕组|銀色子彈字幕組)\\]\\[(名侦探柯南|名偵探柯南)\\]\\[第(\\d+)集([^\\[]*)\\](.*)"
          replace: "[$1][$2 $3$4] Detective Conan $3 $5"

        - match: "\\[(风车字幕组|風車字幕組)\\]\\[(名侦探柯南|名偵探柯南)\\]\\[(\\d+)\\](.*)"
          replace: "[$1][$2] Detective Conan $3 $4"
    serial:
      search:
          
      common:
        - match: "第一季"
          replace: "S1"
        - match: "第二季"
          replace: "S2"
        - match: "第三季"
          replace: "S3"
        - match: "第四季"
          replace: "S4"
        - match: "第五季"
          replace: "S5"
        - match: "第六季"
          replace: "S6"
        - match: "第七季"
          replace: "S7"
        - match: "第八季"
          replace: "S8"
        - match: "Season"
          replace: "S"
        - match: "S0(\\d+)"
          replace: "S$1"
          
      accurate: