logging:
   level:
      root: INFO
      com.lckp.jproxy: INFO

rule:
   location: https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/rule
   location-backup: https://github.rn.lckp.top/LuckyPuppy514/jproxy/main/src/main/resources/rule

time:
   cache-expires: 10080
   token-expires: 10080
   sync-interval: 5
   sync-sonarr-title: 0 0 0/1 * * ?
   sync-sonarr-rule: 0 15 0 * * ?
   sync-radarr-title: 0 30 0/1 * * ?
   sync-radarr-rule: 0 45 1 * * ?

spring:
   type: com.zaxxer.hikari.HikariDataSource
   hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
   datasource:
      url: jdbc:sqlite:./database/jproxy.db
      driver-class-name: org.sqlite.JDBC
   data:
      redis:
         host: ${REDIS_HOST:127.0.0.1}
         port: ${REDIS_PORT:6379}
         database: 0
         lettuce:
            pool:
               max-active: 8
               max-wait: -1
               max-idle: 8
               min-idle: 0
springdoc:
   swagger-ui:
      enabled: false
   api-docs:
      enabled: false
knife4j:
   production: true