spring:
   devtools:
      restart:
         enabled: true # 开启热部署
         additional-paths: src/main/java # 重启目录
         exclude: WEB-INF/** # 不重启目录
   freemarker: # 页面不加载缓存，修改即时生效
      cache: false

api:
  jackett: http://192.168.6.9:9117
  prowlarr: http://192.168.6.9:9696
  format: 
    enable: true
    anime:
      accurate:
        - "{\\[(爱恋&漫猫字幕组|愛戀&漫貓字幕組)\\](.*)\\[([a-zA-Z].*)\\]\\[(\\d+)\\](.*)}:{[$1]$2 $3 $4 $5}"
        - "{【喵萌奶茶屋】.*\\[(.*)/([a-zA-Z].*)\\]\\[(\\d+)\\](.*)}:{[喵萌奶茶屋] $1 / $2 $3 $4}"
        - "{\\[悠哈璃羽字幕社\\] \\[(.*)_(.*)\\] \\[(\\d+)\\](.*)}:{[悠哈璃羽字幕社] $2 $3$4}"
        - "{【(千夏字幕组|千夏字幕組)】【(.*)_(.*)】\\[第(\\d+)(话|話)\\](.*)}:{[$1] $3 $4 $6}"
        - "{\\[(.*)&LoliHouse\\] (.*) / ([\\u4E00-\\u9FA5]+) - (.*) }:{[$1&LoliHouse] $3 / $2 $4}"
        - "{【(幻樱字幕组|幻櫻字幕組)】【(.*)】【([^a-zA-Z]*)([a-zA-Z].*)】【(\\d+)】【([^【】]*)】【([^【】]*)】.*}:{[$1] $3 / $4 $5 [$6][$7]}"
        - "{\\[猎户不鸽发布组\\]( [\\u4E00-\\u9FA5]+[。|？|！]* )(.*) \\[(\\d*)\\](.*)}:{[猎户不鸽发布组] $1/ $2 $3$4}"
        - "{\\[ANi\\] (.*) - (.*)\\s*[-|\\[]\\s*(\\d+)[ \\]](.+)}:{$1 $3 $4}"
        - "{\\[NC-Raws\\] ([\\u4E00-\\u9FA5 。？！]+) \\/ (.*) - (\\d*)(.*)}:{[NC-Raws] $1 / $2 $3$4 [简中\\]}"
        - "{\\[猎户随缘发布组\\] ([\\u4E00-\\u9FA5 。？！]+) (.*) \\[(\\d*)\\](.*)}:{[猎户随缘发布组] $1 / $2 $3$4}"
      common: 
        - "{Season}:{S}"
        - "{S0(\\d)}:{S$1}"
        - "{第二季}:{S2}"
        - "{第三季}:{S3}"
        - "{第四季}:{S4}"
        - "{第五季}:{S5}"
        - "{第六季}:{S6}"
        - "{第七季}:{S7}"
        - "{第八季}:{S8}"
    serial:
      accurate:
      common: 
        - "{Season}:{S}"
        - "{S0(\\d)}:{S$1}"
        - "{第二季}:{S2}"
        - "{第三季}:{S3}"
        - "{第四季}:{S4}"
        - "{第五季}:{S5}"
        - "{第六季}:{S6}"
        - "{第七季}:{S7}"
        - "{第八季}:{S8}"
