server:
  tomcat:
    connection-timeout: 300000

api:
  format: 
    enable: true
    anime:
      searchKey:
        - "{Detective Conan (\\d+)}:{名侦探柯南 $1}"
      accurate:
        - "{\\[Skymoon-Raws\\]\\[(.*) ([^ ]*)\\]\\[(\\d+)](.*)}:{[Skymoon-Raws] $2 / $1 $3 $4}"
        - "{\\[(OPFans枫雪动漫|OPFans楓雪動漫)\\]\\[(.*) ([^ ]*)]\\[第(\\d+)(话|話)\\](.*)}:{[$1] $3 / $2 $4 $6[简体]}"
        - "{\\[(爱恋&漫猫字幕组|愛戀&漫貓字幕組)\\](.*)\\[([a-zA-Z].*)\\]\\[(\\d+)\\](.*)}:{[$1]$2 $3 $4 $5}"
        - "{【喵萌奶茶屋】.*\\[(.*)/([a-zA-Z].*)\\]\\[(\\d+)\\](.*)}:{[喵萌奶茶屋] $1 / $2 $3 $4}"
        - "{\\[悠哈璃羽字幕社\\] \\[(.*)_(.*)\\] \\[(\\d+)\\](.*)}:{[悠哈璃羽字幕社] $2 $3$4}"
        - "{【(千夏字幕组|千夏字幕組)】【(.*)_(.*)】\\[第(\\d+)(话|話)\\](.*)}:{[$1] $3 $4 $6}"
        - "{\\[(.*)&LoliHouse\\] ([a-zA-Z].*) / (.*) - (.*) }:{[$1&LoliHouse] $3 / $2 $4}"
        - "{【(幻樱字幕组|幻櫻字幕組)】【(.*)】【([^a-zA-Z]*)([a-zA-Z].*)】【(\\d+)】【([^【】]*)】【([^【】]*)】.*}:{[$1] $3 / $4 $5 [$6][$7]}"
        - "{\\[猎户不鸽发布组\\] ([^ ]*) (.*) \\[(\\d+)\\](.*)}:{[猎户不鸽发布组] $1 / $2 $3$4}"
        - "{\\[ANi\\] (.*) - (.*)\\s*[-|\\[]\\s*(\\d+)[ \\]](.+)}:{$1 $3 $4[简中]}"
        - "{\\[猎户随缘发布组\\] ([^ ]*) ([a-zA-Z].*) \\[(\\d+)\\](.*)}:{[猎户随缘发布组] $1 / $2 $3$4}"
        - "{\\[Lilith-Raws\\](.*)Shijou Saikyou no Daimaou}:{[Lilith-Raws]$1Shijou Saikyou no Daimaou, Murabito A ni Tensei suru}"
        - "{\\[NC-Raws\\] (.*) \\/ (.*) - (\\d+)(.*)}:{[NC-Raws] $1 / $2 $3$4 [简中\\]}"
        - "{\\[(银色子弹字幕组|銀色子彈字幕組)\\]\\[(名侦探柯南|名偵探柯南)\\]\\[第(\\d+)集([^\\[]*)\\](.*)}:{[$1][$2 $3$4] Detective Conan $3 $5}"
      common: 
        - "{Season}:{S}"
        - "{S0(\\d)}:{S$1}"
        - "{第二季}:{S2}"
        - "{第三季}:{S3}"
        - "{第四季}:{S4}"
        - "{第五季}:{S5}"
        - "{第六季}:{S6}"
        - "{第七季}:{S7}"
        - "{第八季}:{S8}"
    serial:
      accurate:
      common: 
        - "{Season}:{S}"
        - "{S0(\\d)}:{S$1}"
        - "{第二季}:{S2}"
        - "{第三季}:{S3}"
        - "{第四季}:{S4}"
        - "{第五季}:{S5}"
        - "{第六季}:{S6}"
        - "{第七季}:{S7}"
        - "{第八季}:{S8}"
