server:
   port: 8117
   servlet:
      context-path: /
   tomcat:
      relaxed-path-chars: <,>,[,\,],^,`,{,|,}
      relaxed-query-chars: <,>,[,\,],^,`,{,|,}

project:
   code: '@project.artifactId@'
   name: '@project.name@'
   description: '@project.description@'
   version: '@project.version@'

spring:
   jackson:
      default-property-inclusion: NON_NULL
   profiles:
      active:
      - '@spring.profiles.active@'
   liquibase:
      changeLog: classpath:/database/master.xml
   web:
      resources:
         static-locations:
         - classpath:/dist
         - classpath:/rule
   messages:
      basename: locale/messages
   servlet:
      multipart:
         max-file-size: 8MB

mybatis-plus:
   mapper-locations: classpath:/mapper/*.xml
   typeAliasesPackage: '@project.groupId@.@project.artifactId@.entity'
   check-config-location: true
   configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      call-setters-on-nulls: true
      jdbc-type-for-null: null
      auto-mapping-unknown-column-behavior: warning
   global-config:
      banner: false
      db-config:
         id-type: AUTO
         insert-strategy: NOT_NULL
         update-strategy: NOT_NULL
         capital-mode: true
         logic-delete-value: 0
         logic-not-delete-value: 1