spring:
   profiles:
      include: format, format-custom
        
   devtools:
      restart:
         enabled: true # 开启热部署
         additional-paths: src/main/java # 重启目录
         exclude: WEB-INF/** # 不重启目录
   freemarker: # 页面不加载缓存，修改即时生效
      cache: false
   
knife4j:
  basic:
    enable: false #控制是否需要账号密码验证
    username: jproxy  #用户名
    password: jproxy@2022  #密码
  production: false  #控制是否是正产环境，true：生产环境，关闭所有接口文档信息

api:
  jackett: http://192.168.6.9:9117
  prowlarr: http://192.168.6.9:9696
  
task:
  update:
    official:
      cron: 0 0 3 * * ?
      filename: "application-format.yml"
      url: "https://raw.githubusercontent.com/LuckyPuppy514/jproxy/main/src/main/resources/application-format.yml"
      
path:
  profiles:
    official: ""
    custom: ""